title: ChemistryX
description: >-
  UI & UX Designer
  Frontend Developer
url: "https://staging.chemistryx.me"
github: ChemistryX
email: starpiung@naver.com
google_analytics: UA-146771648-1

exclude: [README.md, Gemfile, Gemfile.lock]

comment:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname
  theme: github-light

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
