title: Hyde
description: >-
  Build your own portfolio <br>
  with Hyde.
url: "https://chemistryx.github.io"
baseurl: "/hyde"
github: ChemistryX
email: changeme@chemistryx.me
google_analytics: "UA_TOKEN"

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: "REPO_COMMENTS_PATH"
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
